# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "565c4664a7b842ddeabe5a2dbea1b308"
application_url = "https://example.com"
embedded = true
name = "Billoxi"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_metaobjects,read_metaobjects,write_metaobject_definitions,read_metaobject_definitions,read_orders,read_customers,read_merchant_managed_fulfillment_orders,read_assigned_fulfillment_orders"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
