api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "print-draft-link"
uid = "e4127504-bf71-4521-8f03-28b79b300957b4a43e1b"
type = "ui_extension"

[extensions.capabilities]
api_access = true
network_access = true

[[extensions.targeting]]
module = "./src/Action.jsx"
target = "admin.draft-order-details.action.render"
